apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bookinfo-details.yaml
- bookinfo-ingress.yaml
- bookinfo-mysql.yaml
- bookinfo-ns.yaml
- bookinfo-productpage.yaml
- bookinfo-reviews.yaml
- sleep.yaml

namespace: bookinfo
