apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-date
  namespace: default
spec:
  schedule: "* * * * *" # crontab で起動スケジュールを指定
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 4
      template:
      spec:
        containers: # busybox というイメージで「date」を実行
        - name: print-date
          image: busybox
          command: ["date"]
          restartPolicy: OnFailure